{
  sliders {
    edges {
      node {
        id
        title
        content
        imagendestacada{
          imagen{
            altText
            sourceUrl
          }
        }
      }
    }
  }
}
